### PR TITLE
issue #94 - fix grid overflow problem

### PR DESCRIPTION
**Pull request by kotzendekrabbe**
Please test - if you want this change please beware of the following things:
- you need a wrapper over all grid sections with the class main (line: 192)
- the main class is the only html change which will be needed

after this PR we don't have a flyout problem - described here #94 - anymore

### CODE REVIEW

**Comment by zoepage** [comment]
So this means, every time I need a full-width box, I use `div.main` correct? 
And otherwise nothing changed in general?

**Comment by kotzendekrabbe** [comment]
@zoepage 
No, not exactly. We need a element with class main at all pages as wrapper to fix the full width AND overflow problem (like for the filter option issues dropdown/flyout) :)

**Comment by zoepage** [comment]
So we could simply add it to the main layout template to the body tag or one level below? :)

**Comment by kotzendekrabbe** [comment]
sadly, that doesn't work. it has to be a level below, any wrapper around the sections

**Comment by zoepage** [comment]
@kotzendekrabbe  for every section or just the ones that need the flyout?
(Sorry for not getting it 🙈)

**Comment by kotzendekrabbe** [comment]
@zoepage 

```
<div class="main">
    <section class="grid"> 
    <section class="grid">
    <section class="grid" >
    ...
</div>
```


is that more clear? otherwise let's do a call? :)

**Comment by zoepage** [comment]
Oh, this is how we do it anyway right now :)))) perfect!

**Comment by zoepage** [comment]
Just a FYI
I'll merge the PR as soon as I have finished the PR I am working on right now (navigation).

**Review by zoepage — APPROVED** [review]

**Pull request merged**
