### PR TITLE
Fixes #15 - added detail issue module

### LINKED ISSUE #15: add issue detail module

### PR DESCRIPTION
**Pull request by zoepage**
- [x] add issue detail module
- [x] add comment module
- [x] add upload module for comments
- [x] add code example with "new" highlighter
- [x] box for label, which is fixed

### CODE REVIEW

**Comment by zoepage** [comment]
@kotzendekrabbe could you check the merge conflicts? But probably best after last PR.

**Comment by lewiscowper** [comment]
@kotzendekrabbe @zoepage have added the issue comments back in, and updated the styles for the comment box. (not the input yet, but that'll be next)

**Comment by lewiscowper** [comment]
@zoepage @kotzendekrabbe I've uploaded the new comment box now, but the styling leaves a little to be desired. Feel free to adjust/comment here and I can fix things.

**Comment by lewiscowper** [comment]
I've tested the code highlighting by adding a script tag with the JS that is presumably on the webcompat.com page, and it works, but right now the JS is not on the page, but yeah, all looks good to me aside from doing a test of inline images in the comments?

**Pull request merged**
