### PR TITLE
Revert "issue #94 - fix grid overflow problem"

### PR DESCRIPTION
**Pull request by zoepage**
Reverts webcompat/design#95

### CODE REVIEW

**Comment by zoepage** [comment]
@kotzendekrabbe After merging, I saw the whole `.grid` sections were overflowing... 🤔

**Comment by kotzendekrabbe** [comment]
@zoepage let me check this tomorrow - need enough time to concentrate on it

**Comment by zoepage** [comment]
💜

**Comment by kotzendekrabbe** [comment]
@zoepage I don't have this problem - let us make a call about it - think that's easier.

**Pull request closed without merging**
